### ISSUE TITLE
Got an issue regarding stdout veritrans.log on heroku

### ISSUE THREAD

**Issue by ferryphang** [veritrans/veritrans-ruby#27]
Hi, i just try SNAP on my staging server hosted in heroku and i facing an error cannot create_widget_token as i debug i see that this gem need to log on a veritrans.log file. This is because i add .gitignore for /log folder so this gem didnt found the veritrans.log. Did you intend to patch this because right now my solution is i dont ignore veritrans.log file on my gitignore but this will be problematic when i need to ignore development.log, sidekiq.log something like that one by one.

**Comment by Paxa** [comment]
> i see that this gem need to log on a veritrans.log
Error message is about missing folder or permission denied?

If there is no `log/veritrans.log` - it will create a new files, if folder not exists then I think it should be fixed.

If you wish to have all logs in stdout (useful for log aggregation), you can do:
```ruby
Midtrans.file_logger = Rails.logger
# or
Midtrans.file_logger = Logger.new(STDOUT)
```

To save in different file:
```ruby
Midtrans.file_logger = Logger.new(Rails.root.join("some_folder/snap.log").to_s)
```

I think rails applications always folder `log` with empty file `log/.keep` (in order to keep folder in git) and `.gitignore` [has something](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/gitignore#L17) like: `/log/*` (ignore all files inside log folder but not the folder itself)
I would recommend to keep `log` folder because some other libraries may expect that it's exists.


Thanks for reporting, will add some changes in next version

**Comment by ferryphang** [comment]
Thanks for the solution... here is some of the screenshot i got on a papertrail log on heroku if you need.
![banners_and_alerts_and_1__heroku_console__node_](https://user-images.githubusercontent.com/4382692/28487859-091401a6-6ec5-11e7-8b95-a0427b60090a.png)

**Comment by Andrenzo17** [comment]
Hi @ferryphang are you still get error using heroku?
i have tried test Midtrans Ruby library version 2.4.0 and can run in heroku https://sinatra-example-demo.herokuapp.com/
https://github.com/veritrans/veritrans-ruby/tree/master/example/sinatra

I think the best practice is running the file than using irb. Here is the example Midtrans snap that you can check https://github.com/veritrans/veritrans-ruby/tree/master/example/snap

Thank you
